name: Production

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create .env from GitHub Secrets
        run: |
          echo REACT_APP_MAPTILER_KEY="${{ secrets.MAPTILER_KEY }}" >> .env
          echo REACT_APP_GRAPH_API_TOKEN="${{ secrets.GRAPH_API_TOKEN }}" >> .env
          echo REACT_APP_META_APP_ID="${{ secrets.META_APP_ID }}" >> .env

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
