name: Production

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.MAPTILER_API_KEY }}" ]; then
            echo "Erro: MAPTILER_API_KEY não definido."
            exit 1
          fi
          if [ -z "${{ secrets.MAPTILER_DATASET_ID }}" ]; then
            echo "Erro: MAPTILER_DATASET_ID não definido."
            exit 1
          fi
          if [ -z "${{ secrets.META_API_ACCESS }}" ]; then
            echo "Erro: META_API_ACCESS não definido."
            exit 1
          fi

      - name: Create .env from GitHub Secrets
        run: |
          echo REACT_APP_MAPTILER_API_KEY="${{ secrets.MAPTILER_API_KEY }}" >> .env
          echo REACT_APP_MAPTILER_DATASET_ID="${{ secrets.MAPTILER_DATASET_ID }}" >> .env
          echo REACT_APP_META_API_ACCESS="${{ secrets.META_API_ACCESS }}" >> .env

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
